### ISSUE TITLE
Generating invalid MEI

### ISSUE THREAD

**Issue by JRegimbal** [DDMAL/MEI_encoding#1]
The current develop version generates invalid MEI. From first glance, this includes adding `@line` to `nc` and adding `pname=None` and `octave=None`. Also the correct attribute is `@oct` and not `@octave`.

**Comment by timothydereuse** [comment]
Should be fixed with https://github.com/DDMAL/MEI_encoding/commit/45ac76cd32bfbe22db8f90d6efc6885fdd9e58cf.
