### ISSUE TITLE
Bounding box not being referenced by any element in the <body> part

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/MEI_encoding#26]
[012r invalid and absent.zip](https://github.com/DDMAL/MEI_encoding/files/6570223/012r.invalid.and.absent.zip)
In the above folio, there is a line of coordinates for BBs (line 192) that doesn't refer to any element in the `<body>` part of the code. We think this is related to an earlier fix wherein empty syllables were deleted, but the coordinates of their BBs weren't (I am currently searching for the issue referencing that fix and will update this post once I find it).

@martha-thomae suggests implementing a rule like: If a bbox (`<zone>` element) has an `@xml:id` that has no `@facs` associated in the `<body>` section of the MEI file, then it should be deleted

https://github.com/DDMAL/MEI_encoding/issues/24: This issue is linked to the negative ulx coordinate issue, in that when a BB with a negative coordinate also happens to be a BB that doesn't refer to anything, Neon reads the file as invalid, but there's no way for us to fix it (using Neon, at least). In fact, the negative ulx problem is how we discovered this issue in the first place, because there was no escapee BB to drag to its proper place.

**Comment by carrieeex** [comment]
For folio 012r and other similar folios with this issue ([invalid ulx](https://github.com/DDMAL/MEI_encoding/issues/24), here with no `<body>` element):
Not sure where exactly this invalid attribute comes from, but to make this MEI valid, we can delete that line in the MEI file and put it back to Neon.
For example, for 012r, the log file tells us the invalid attribute is in line 208:
```
file_0.xml:208: element zone: Relax-NG validity error : Invalid attribute ulx for element zone
```
and in the MEI file it is:
```
                <zone xml:id="m-98796dce-7354-41c8-b404-9ef9798961a8" lry="4538" lrx="233" ulx="-1" uly="4290"/>
```
which contains "ulx=-1". Deleting the whole line and put it back to Neon would make this valid for further corrections.
[012r invalid validation.log](https://github.com/DDMAL/MEI_encoding/files/6879784/012r.invalid.validation.log)
[012r invalid.zip](https://github.com/DDMAL/MEI_encoding/files/6879785/012r.invalid.zip)

**Comment by JoyfulGen** [comment]
This issue hasn't happened in ages, so I'll go ahead and close it!
