### ISSUE TITLE
Syllable doesn't have an actual syllable (?)

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/MEI_encoding#29]
I came across this phenomenon while correcting A02r (Salzinnes): there's a little diamond in the text section of Neon that, as far as I can tell, doesn't correspond to any bounding box or neume.
<img width="1349" alt="A02r where be syllable" src="https://user-images.githubusercontent.com/83373378/121915504-41f26c80-cd01-11eb-9256-976d9929038d.png">
I tried erasing all the neumes of the line, the mystery diamond remained. Since clicking on the diamond only opens up the text input box, there's no way I can erase it.

I looked at the MEI file, and to my (very) limited understanding it looks like the syllable element just doesn't have a syllable. It has a neume, but no neume components! I had never seen this issue before.

The MEI file: [A02r ghost syllable.zip](https://github.com/DDMAL/MEI_encoding/files/6649433/A02r.ghost.syllable.zip)
The offending MEI snippet:
 ``` </syllable>
                                <syllable xml:id="syllable-0000001059010165">
                                    <neume xml:id="neume-0000001627436955"/>
                                    <syl xml:id="syl-0000001102000456" facs="#zone-0000002000126367"/>

**Comment by JoyfulGen** [comment]
It happened again! A27r, last line, between the syllables of "san-cto."

The MEI file: 
[A27r ghost syllable.zip](https://github.com/DDMAL/MEI_encoding/files/6678622/A27r.ghost.syllable.zip)

The offending MEI snippet: 
```</syllable>
                                <syllable xml:id="m-3f495202-f7e4-4161-b30e-9af3e22769df">
                                    <syl xml:id="m-1c1ea46c-af55-4f50-bcf7-40820f30b418" facs="#m-705dd01e-3ecd-48d8-bd75-f301031eb8b2"/>
                                    <neume xml:id="neume-0000000042694414"/>

**Comment by JoyfulGen** [comment]
It also happened in A21r. Just to make sure all the files are in the same place, here are the three ghost syllable files, all corrected but still containing the problematic empty syllable:
[Neon - Corrected A02r ghost syllable.mei.zip](https://github.com/DDMAL/MEI_encoding/files/6694157/Neon.-.Corrected.A02r.ghost.syllable.mei.zip)
[Neon - Corrected A21r ghost syllable.mei.zip](https://github.com/DDMAL/MEI_encoding/files/6694159/Neon.-.Corrected.A21r.ghost.syllable.mei.zip)
[Neon - Corrected A27r ghost syllable.mei.zip](https://github.com/DDMAL/MEI_encoding/files/6694163/Neon.-.Corrected.A27r.ghost.syllable.mei.zip)

**Comment by carrieeex** [comment]
It also happened in A08v when I was using Neon in Rodan2, where a mysterious text has no bounding boxes associated (here I selected everything on the last three staves and the mysterious text cannot be selected):
![image](https://user-images.githubusercontent.com/59303880/124801114-746c3f80-df24-11eb-9dee-22f43c7b50ff.png)

The solution as @JoyfulGen mentioned in the comments above is that we can delete the weird syllable in the MEI file (line 1808-1811, after the custos of the second last staff):
```
                                <syllable xml:id="syllable-0000001036625520">
                                    <neume xml:id="neume-0000001758199546"/>
                                    <syl xml:id="syl-0000000440211680" facs="#zone-0000000322773175">?????</syl>
                                </syllable>
```
and I've also checked that zone, it seems that it has no `ulx` coordinate (line 604):
```
                <zone xml:id="zone-0000000322773175" uly="100" lrx="100" lry="200"/>
```
and here's the MEI file of A08v: 
[A08v weird order and bbox.zip](https://github.com/DDMAL/MEI_encoding/files/6778991/A08v.weird.order.and.bbox.zip)
