### ISSUE TITLE
If staves wrong colour, MEI-encoding job fails

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/MEI_encoding#36]
The vast majority of Einsiedeln folios have black staff lines, so when then training models for Einsiedeln were created, that's what they were taught with. However, the final eight folios of the manuscript include red staff lines; in this case, the red lines aren't read as staff lines, so the glyphs on them aren't recognized either and there's nothing there. That's not a huge problem, because there are black staves too and those are identified just fine.

The issue is that there are four folios (278v, 279r, 279v, 280v) that contain only red staff lines. When I ran them, none of the staves were identified, so not one glyph was found and the MEI-encoding job failed. 

This is, therefore, not really a request for a fix, more of a friendly warning: if the staves on a folio are a different colour than the ones used for training, the MEI-encoding job will fail. (And, to a non-coding expert, it won't be clear as to why!)

**Comment by annamorphism** [comment]
@JoyfulGen so does this mean that if manuscripts have more than one type of staff present (red AND black) the training needs to happen on both kinds?

**Comment by JoyfulGen** [comment]
Yes I believe so!

**Comment by JoyfulGen** [comment]
I've included a note about this in the new OMR documentation here: https://github.com/DDMAL/e2e-omr-resources/wiki/2.0-Pixel-and-layer-separation-training

As well as in the FAQ: https://github.com/DDMAL/e2e-omr-resources/wiki/FAQ#the-staff-lines-change-colour-in-a-section-of-my-manuscript-and-now-mei-encoding-is-failing
